tests.c File Reference
#include <stdbool.h>
#include `tests.h`
#include `production.h`
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
bool tests (void)
bool testReadInput (void)
bool testMakeArrays (void)
bool testPlayOne (void)
bool testNeighbors (void)
bool testAnyX (void)
bool testSameContent (void)
Function Documentation
testAnyX()
bool testAnyX (void)
Tests to make sure that anyX can find an x in an array
Parameters
none
Returns
true if succeed, false otherwise
References anyX().
Referenced by tests().
testMakeArrays()
bool testMakeArrays (void)
Tests creating an array and populating it
Parameters
none
Returns
true if succeed, false otherwise
Referenced by tests().
testNeighbors()
bool testNeighbors (void)
Tests to make sure that the correct number of neighbors are counted around a position in an array.
Parameters
none
Returns
true if succeed, false otherwise
References HowManyNeighbors().
Referenced by tests().
testPlayOne()
bool testPlayOne (void)
Tests to make sure playOne works and generates the correct nextBoard
Parameters
none
Returns
true if succeed, false otherwise
References PlayOne().
Referenced by tests().
testReadInput()
bool testReadInput (void)
Tests reading a file into an array
Parameters
none
Returns
true if succeed, false otherwise
Referenced by tests().
tests()
bool tests (void)
Tests all the functions in this file to make sure they work
Parameters
none
Returns
bool true if all pass, false if at least one fails
References testAnyX(), testMakeArrays(), testNeighbors(), testPlayOne(), testReadInput(), and testSameContent().
Referenced by main().
testSameContent()
bool testSameContent (void)
Tests to see if the sameContent function works
Parameters
none
Returns
true if succeed, false otherwise.
References sameContent().
Referenced by tests().